name: Luau Benchmarks (Tag)

on:
  workflow_dispatch:

jobs:
  benchmarks-run:
    name: Run ${{ matrix.bench.title }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        engine:
          - { channel: stable, version: latest, runner: "robloxdev-cli" }
          # - { channel: develop, version: latest, runner: 'robloxdev-cli' }
          # covers environment closest to RobloxStudio, but not available on Linux
          # - { channel: develop, version: latest, runner: 'roblox-cli'}
        bench:
          - {
              script: "run-benchmarks",
              timeout: 12,
              title: "Luau Benchmarks",
              cachegrindTitle: "Performance",
              cachegrindIterCount: 20,
            }
        tag:
          - "0.500"
          - "0.501"
          - "0.502"
          - "0.503"
          - "0.504"
          - "0.505"
          - "0.506"
          - "0.507"
          - "0.508"
          - "0.509"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.tag }}

      - name: Build Luau
        run: make config=release luau luau-analyze

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install requests
        run: python -m pip install requests

      - name: Run benchmark
        run: python bench/bench.py | tee ${{ matrix.bench.script }}-output.txt

      - name: Navigate to root dir, create gh-pages dir then navigate into it
        run: cd .. && mkdir gh-pages && cd gh-pages

      - name: Switch to & checkout gh-pages repo
        uses: actions/checkout@v3
        with:
          repository: AllanJeremy/luau-benchmark-results
          ref: "main"

      - name: Checkout gh-pages
        run: |
          git status
          git fetch --no-tags --depth=1 origin gh-pages
          git checkout --track origin/gh-pages
          git pull
          git status

      - name: Navigate back to luau before checking out original repo
        run: cd ..

      #Run `github-action-benchmark` action
      - name: Store ${{ matrix.bench.title }} result
        uses: Roblox/rhysd-github-action-benchmark@v-luau
        with:
          name: ${{ matrix.bench.title }}
          tool: "benchmarkluau"
          output-file-path: ../${{ matrix.bench.script }}-output.txt
          external-data-json-path: ../gh-pages/dev/bench/data-historical.json
          alert-threshold: 150%
          fail-threshold: 200%
          fail-on-alert: true
          comment-on-alert: true
          comment-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push benchmark results
        run: |
          git add ../gh-pages/dev/bench/data-historical.json
          git commit -m "Add benchmarks results for ${{ matrix.tag }}"
          git push -u origin main
