name: Luau Benchmarks

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "papers/**"
      - "rfcs/**"
      - "*.md"
      - "prototyping/**"

jobs:
  benchmarks-run:
    name: Run ${{ matrix.bench.title }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        engine:
          - { channel: stable, version: latest, runner: "robloxdev-cli" }
          # - { channel: develop, version: latest, runner: 'robloxdev-cli' }
          # covers environment closest to RobloxStudio, but not available on Linux
          # - { channel: develop, version: latest, runner: 'roblox-cli'}
        bench:
          - {
              script: "run-benchmarks",
              timeout: 12,
              title: "Luau Benchmarks",
              cachegrindTitle: "Performance",
              cachegrindIterCount: 20,
            }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Luau
        run: make config=release luau luau-analyze

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install requests
        run: python -m pip install requests && pwd

      - name: Run benchmark
        run: |
          python bench/bench.py | tee ../${{ matrix.bench.script }}-output.txt

      - name: Print parent directory
        run: cd .. && ls

      - name: Cd 1 level up and create gh-pages dir then cd into it
        run: ls && cd .. && mkdir gh-pages && cd gh-pages && pwd && ls

      - name: Switch to & checkout gh-pages repo
        uses: actions/checkout@v3
        with:
          repository: AllanJeremy/luau-benchmark-results
          ref: "main"

      - name: Checkout gh-pages
        run: |
          git status
          git fetch --no-tags --depth=1 origin main
          git checkout main
          git pull
          git status

      - name: Cd back to luau before checking out original repo
        run: cd .. && pwd && ls

      - name: Switch to original luau repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Print current directory & list files
        run: pwd && ls

      #Run `github-action-benchmark` action
      - name: Store ${{ matrix.bench.title }} result
        uses: Roblox/rhysd-github-action-benchmark@v-luau
        with:
          name: ${{ matrix.bench.title }}
          tool: "benchmarkluau"
          # This should come from Luau repo
          output-file-path: ${{ matrix.bench.script }}-output.txt

          # This should map to thebenchmark results repo
          external-data-json-path: ../gh-pages/dev/bench/data.json
          alert-threshold: 150%
          fail-threshold: 200%
          fail-on-alert: true
          comment-on-alert: true
          comment-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
