name: "Do something"
on:
  push:
jobs:
  doing-something:
    runs-on: "ubuntu-latest"
    name: Our main job (the caller)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Something happening internally, kwa ground
        run: |
          echo 'Tupo site'

      - name: Use the reusable workflow
        uses: ./.github/workflows/custom-action
        with:
          first_name: "Allan"
