name: Setup Luau

on:
  workflow_call:
    inputs:
      runsOn:
        required: true
        type: string

jobs:
  setup-luau:
    name: Setup Luau
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Luau
        run: make config=release luau luau-analyze

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install python dependencies
        run: |
          python -m pip install requests
          python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
